#############################################################################
# Makefile for building: I-rover
# Generated by qmake (2.01a) (Qt 4.8.3) on: mar. déc. 11 13:15:37 2012
# Project:  I-rover.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile I-rover.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc/ihm -Isrc/ihm/widgets -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/ihm/main.cpp \
		src/ihm/mainwindow.cpp \
		src/ihm/widgets/aboutdialog.cpp \
		src/ihm/widgets/leftmenu.cpp \
		src/ihm/widgets/mapmenu.cpp \
		src/ihm/widgets/mission.cpp \
		src/ihm/widgets/robotmenu.cpp moc_mainwindow.cpp \
		moc_aboutdialog.cpp \
		moc_leftmenu.cpp \
		moc_mapmenu.cpp \
		moc_mission.cpp \
		moc_robotmenu.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		aboutdialog.o \
		leftmenu.o \
		mapmenu.o \
		mission.o \
		robotmenu.o \
		moc_mainwindow.o \
		moc_aboutdialog.o \
		moc_leftmenu.o \
		moc_mapmenu.o \
		moc_mission.o \
		moc_robotmenu.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		I-rover.pro
QMAKE_TARGET  = I-rover
DESTDIR       = 
TARGET        = I-rover

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_aboutdialog.h ui_leftmenu.h ui_mapmenu.h ui_mission.h ui_robotmenu.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: I-rover.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile I-rover.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile I-rover.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/I-rover1.0.0 || $(MKDIR) .tmp/I-rover1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/I-rover1.0.0/ && $(COPY_FILE) --parents confdefs.h config.h ui_robotinformation.h src/ihm/mainwindow.h src/ihm/widgets/aboutdialog.h src/ihm/widgets/leftmenu.h src/ihm/widgets/mapmenu.h src/ihm/widgets/mission.h src/ihm/widgets/robotmenu.h .tmp/I-rover1.0.0/ && $(COPY_FILE) --parents src/ihm/resources.qrc .tmp/I-rover1.0.0/ && $(COPY_FILE) --parents src/ihm/main.cpp src/ihm/mainwindow.cpp src/ihm/widgets/aboutdialog.cpp src/ihm/widgets/leftmenu.cpp src/ihm/widgets/mapmenu.cpp src/ihm/widgets/mission.cpp src/ihm/widgets/robotmenu.cpp .tmp/I-rover1.0.0/ && $(COPY_FILE) --parents src/ihm/mainwindow.ui src/ihm/widgets/aboutdialog.ui src/ihm/widgets/leftmenu.ui src/ihm/widgets/mapmenu.ui src/ihm/widgets/mission.ui src/ihm/widgets/robotmenu.ui .tmp/I-rover1.0.0/ && (cd `dirname .tmp/I-rover1.0.0` && $(TAR) I-rover1.0.0.tar I-rover1.0.0 && $(COMPRESS) I-rover1.0.0.tar) && $(MOVE) `dirname .tmp/I-rover1.0.0`/I-rover1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/I-rover1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_aboutdialog.cpp moc_leftmenu.cpp moc_mapmenu.cpp moc_mission.cpp moc_robotmenu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_aboutdialog.cpp moc_leftmenu.cpp moc_mapmenu.cpp moc_mission.cpp moc_robotmenu.cpp
moc_mainwindow.cpp: src/ihm/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/mainwindow.h -o moc_mainwindow.cpp

moc_aboutdialog.cpp: src/ihm/widgets/aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/widgets/aboutdialog.h -o moc_aboutdialog.cpp

moc_leftmenu.cpp: src/ihm/widgets/leftmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/widgets/leftmenu.h -o moc_leftmenu.cpp

moc_mapmenu.cpp: src/ihm/widgets/mapmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/widgets/mapmenu.h -o moc_mapmenu.cpp

moc_mission.cpp: src/ihm/widgets/mission.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/widgets/mission.h -o moc_mission.cpp

moc_robotmenu.cpp: src/ihm/widgets/robotmenu.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ihm/widgets/robotmenu.h -o moc_robotmenu.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: src/ihm/resources.qrc \
		src/ihm/resources/backgrounds/bg-leftmenu.png \
		src/ihm/resources/icons/retract2Top.png \
		src/ihm/resources/icons/retractArrow.png \
		src/ihm/resources/icons/about.png \
		src/ihm/resources/icons/deployArrow.png \
		src/ihm/resources/icons/deploy2bottom.png \
		src/ihm/resources/icons/quit.png
	/usr/bin/rcc -name resources src/ihm/resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_aboutdialog.h ui_leftmenu.h ui_mapmenu.h ui_mission.h ui_robotmenu.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_aboutdialog.h ui_leftmenu.h ui_mapmenu.h ui_mission.h ui_robotmenu.h
ui_mainwindow.h: src/ihm/mainwindow.ui \
		src/ihm/widgets/leftmenu.h
	/usr/bin/uic-qt4 src/ihm/mainwindow.ui -o ui_mainwindow.h

ui_aboutdialog.h: src/ihm/widgets/aboutdialog.ui
	/usr/bin/uic-qt4 src/ihm/widgets/aboutdialog.ui -o ui_aboutdialog.h

ui_leftmenu.h: src/ihm/widgets/leftmenu.ui \
		src/ihm/widgets/mapmenu.h \
		src/ihm/widgets/robotmenu.h
	/usr/bin/uic-qt4 src/ihm/widgets/leftmenu.ui -o ui_leftmenu.h

ui_mapmenu.h: src/ihm/widgets/mapmenu.ui
	/usr/bin/uic-qt4 src/ihm/widgets/mapmenu.ui -o ui_mapmenu.h

ui_mission.h: src/ihm/widgets/mission.ui
	/usr/bin/uic-qt4 src/ihm/widgets/mission.ui -o ui_mission.h

ui_robotmenu.h: src/ihm/widgets/robotmenu.ui \
		src/ihm/widgets/mission.h
	/usr/bin/uic-qt4 src/ihm/widgets/robotmenu.ui -o ui_robotmenu.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/ihm/main.cpp src/ihm/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/ihm/main.cpp

mainwindow.o: src/ihm/mainwindow.cpp src/ihm/mainwindow.h \
		ui_mainwindow.h \
		src/ihm/widgets/leftmenu.h \
		src/ihm/widgets/aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/ihm/mainwindow.cpp

aboutdialog.o: src/ihm/widgets/aboutdialog.cpp src/ihm/widgets/aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o src/ihm/widgets/aboutdialog.cpp

leftmenu.o: src/ihm/widgets/leftmenu.cpp src/ihm/widgets/leftmenu.h \
		ui_leftmenu.h \
		src/ihm/widgets/mapmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o leftmenu.o src/ihm/widgets/leftmenu.cpp

mapmenu.o: src/ihm/widgets/mapmenu.cpp src/ihm/widgets/mapmenu.h \
		ui_mapmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapmenu.o src/ihm/widgets/mapmenu.cpp

mission.o: src/ihm/widgets/mission.cpp src/ihm/widgets/mission.h \
		ui_mission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mission.o src/ihm/widgets/mission.cpp

robotmenu.o: src/ihm/widgets/robotmenu.cpp src/ihm/widgets/robotmenu.h \
		ui_robotmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotmenu.o src/ihm/widgets/robotmenu.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_leftmenu.o: moc_leftmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_leftmenu.o moc_leftmenu.cpp

moc_mapmenu.o: moc_mapmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapmenu.o moc_mapmenu.cpp

moc_mission.o: moc_mission.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mission.o moc_mission.cpp

moc_robotmenu.o: moc_robotmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotmenu.o moc_robotmenu.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

